
export interface Surah {
  id: number; // Surah number (1-114)
  name: string; // Arabic name
  englishName: string; // Transliterated name
  totalVerses: number;
}

export const surahData: Surah[] = [
  { "id": 1, "name": "الفاتحة", "englishName": "Al-Fatiha", "totalVerses": 7 },
  { "id": 2, "name": "البقرة", "englishName": "Al-Baqara", "totalVerses": 286 },
  { "id": 3, "name": "آل عمران", "englishName": "Aal-i-Imran", "totalVerses": 200 },
  { "id": 4, "name": "النساء", "englishName": "An-Nisa", "totalVerses": 176 },
  { "id": 5, "name": "المائدة", "englishName": "Al-Ma'ida", "totalVerses": 120 },
  { "id": 6, "name": "الأنعام", "englishName": "Al-An'am", "totalVerses": 165 },
  { "id": 7, "name": "الأعراف", "englishName": "Al-A'raf", "totalVerses": 206 },
  { "id": 8, "name": "الأنفال", "englishName": "Al-Anfal", "totalVerses": 75 },
  { "id": 9, "name": "التوبة", "englishName": "At-Tawba", "totalVerses": 129 },
  { "id": 10, "name": "يونس", "englishName": "Yunus", "totalVerses": 109 },
  { "id": 11, "name": "هود", "englishName": "Hud", "totalVerses": 123 },
  { "id": 12, "name": "يوسف", "englishName": "Yusuf", "totalVerses": 111 },
  { "id": 13, "name": "الرعد", "englishName": "Ar-Ra'd", "totalVerses": 43 },
  { "id": 14, "name": "ابراهيم", "englishName": "Ibrahim", "totalVerses": 52 },
  { "id": 15, "name": "الحجر", "englishName": "Al-Hijr", "totalVerses": 99 },
  { "id": 16, "name": "النحل", "englishName": "An-Nahl", "totalVerses": 128 },
  { "id": 17, "name": "الإسراء", "englishName": "Al-Isra", "totalVerses": 111 },
  { "id": 18, "name": "الكهف", "englishName": "Al-Kahf", "totalVerses": 110 },
  { "id": 19, "name": "مريم", "englishName": "Maryam", "totalVerses": 98 },
  { "id": 20, "name": "طه", "englishName": "Taha", "totalVerses": 135 },
  { "id": 21, "name": "الأنبياء", "englishName": "Al-Anbiya", "totalVerses": 112 },
  { "id": 22, "name": "الحج", "englishName": "Al-Hajj", "totalVerses": 78 },
  { "id": 23, "name": "المؤمنون", "englishName": "Al-Muminun", "totalVerses": 118 },
  { "id": 24, "name": "النور", "englishName": "An-Nur", "totalVerses": 64 },
  { "id": 25, "name": "الفرقان", "englishName": "Al-Furqan", "totalVerses": 77 },
  { "id": 26, "name": "الشعراء", "englishName": "Ash-Shu'ara", "totalVerses": 227 },
  { "id": 27, "name": "النمل", "englishName": "An-Naml", "totalVerses": 93 },
  { "id": 28, "name": "القصص", "englishName": "Al-Qasas", "totalVerses": 88 },
  { "id": 29, "name": "العنكبوت", "englishName": "Al-Ankabut", "totalVerses": 69 },
  { "id": 30, "name": "الروم", "englishName": "Ar-Rum", "totalVerses": 60 },
  { "id": 31, "name": "لقمان", "englishName": "Luqman", "totalVerses": 34 },
  { "id": 32, "name": "السجدة", "englishName": "As-Sajda", "totalVerses": 30 },
  { "id": 33, "name": "الأحزاب", "englishName": "Al-Ahzab", "totalVerses": 73 },
  { "id": 34, "name": "سبإ", "englishName": "Saba", "totalVerses": 54 },
  { "id": 35, "name": "فاطر", "englishName": "Fatir", "totalVerses": 45 },
  { "id": 36, "name": "يس", "englishName": "Ya-Sin", "totalVerses": 83 },
  { "id": 37, "name": "الصافات", "englishName": "As-Saffat", "totalVerses": 182 },
  { "id": 38, "name": "ص", "englishName": "Sad", "totalVerses": 88 },
  { "id": 39, "name": "الزمر", "englishName": "Az-Zumar", "totalVerses": 75 },
  { "id": 40, "name": "غافر", "englishName": "Ghafir", "totalVerses": 85 },
  { "id": 41, "name": "فصلت", "englishName": "Fussilat", "totalVerses": 54 },
  { "id": 42, "name": "الشورى", "englishName": "Ash-Shuraa", "totalVerses": 53 },
  { "id": 43, "name": "الزخرف", "englishName": "Az-Zukhruf", "totalVerses": 89 },
  { "id": 44, "name": "الدخان", "englishName": "Ad-Dukhan", "totalVerses": 59 },
  { "id": 45, "name": "الجاثية", "englishName": "Al-Jathiya", "totalVerses": 37 },
  { "id": 46, "name": "الأحقاف", "englishName": "Al-Ahqaf", "totalVerses": 35 },
  { "id": 47, "name": "محمد", "englishName": "Muhammad", "totalVerses": 38 },
  { "id": 48, "name": "الفتح", "englishName": "Al-Fath", "totalVerses": 29 },
  { "id": 49, "name": "الحجرات", "englishName": "Al-Hujurat", "totalVerses": 18 },
  { "id": 50, "name": "ق", "englishName": "Qaf", "totalVerses": 45 },
  { "id": 51, "name": "الذاريات", "englishName": "Adh-Dhariyat", "totalVerses": 60 },
  { "id": 52, "name": "الطور", "englishName": "At-Tur", "totalVerses": 49 },
  { "id": 53, "name": "النجم", "englishName": "An-Najm", "totalVerses": 62 },
  { "id": 54, "name": "القمر", "englishName": "Al-Qamar", "totalVerses": 55 },
  { "id": 55, "name": "الرحمن", "englishName": "Ar-Rahman", "totalVerses": 78 },
  { "id": 56, "name": "الواقعة", "englishName": "Al-Waqi'a", "totalVerses": 96 },
  { "id": 57, "name": "الحديد", "englishName": "Al-Hadid", "totalVerses": 29 },
  { "id": 58, "name": "المجادلة", "englishName": "Al-Mujadila", "totalVerses": 22 },
  { "id": 59, "name": "الحشر", "englishName": "Al-Hashr", "totalVerses": 24 },
  { "id": 60, "name": "الممتحنة", "englishName": "Al-Mumtahina", "totalVerses": 13 },
  { "id": 61, "name": "الصف", "englishName": "As-Saff", "totalVerses": 14 },
  { "id": 62, "name": "الجمعة", "englishName": "Al-Jumu'a", "totalVerses": 11 },
  { "id": 63, "name": "المنافقون", "englishName": "Al-Munafiqun", "totalVerses": 11 },
  { "id": 64, "name": "التغابن", "englishName": "At-Taghabun", "totalVerses": 18 },
  { "id": 65, "name": "الطلاق", "englishName": "At-Talaq", "totalVerses": 12 },
  { "id": 66, "name": "التحريم", "englishName": "At-Tahrim", "totalVerses": 12 },
  { "id": 67, "name": "الملك", "englishName": "Al-Mulk", "totalVerses": 30 },
  { "id": 68, "name": "القلم", "englishName": "Al-Qalam", "totalVerses": 52 },
  { "id": 69, "name": "الحاقة", "englishName": "Al-Haaqqa", "totalVerses": 52 },
  { "id": 70, "name": "المعارج", "englishName": "Al-Ma'arij", "totalVerses": 44 },
  { "id": 71, "name": "نوح", "englishName": "Nuh", "totalVerses": 28 },
  { "id": 72, "name": "الجن", "englishName": "Al-Jinn", "totalVerses": 28 },
  { "id": 73, "name": "المزمل", "englishName": "Al-Muzzammil", "totalVerses": 20 },
  { "id": 74, "name": "المدثر", "englishName": "Al-Muddaththir", "totalVerses": 56 },
  { "id": 75, "name": "القيامة", "englishName": "Al-Qiyama", "totalVerses": 40 },
  { "id": 76, "name": "الانسان", "englishName": "Al-Insan", "totalVerses": 31 },
  { "id": 77, "name": "المرسلات", "englishName": "Al-Mursalat", "totalVerses": 50 },
  { "id": 78, "name": "النبإ", "englishName": "An-Naba", "totalVerses": 40 },
  { "id": 79, "name": "النازعات", "englishName": "An-Nazi'at", "totalVerses": 46 },
  { "id": 80, "name": "عبس", "englishName": "Abasa", "totalVerses": 42 },
  { "id": 81, "name": "التكوير", "englishName": "At-Takwir", "totalVerses": 29 },
  { "id": 82, "name": "الإنفطار", "englishName": "Al-Infitar", "totalVerses": 19 },
  { "id": 83, "name": "المطففين", "englishName": "Al-Mutaffifin", "totalVerses": 36 },
  { "id": 84, "name": "الإنشقاق", "englishName": "Al-Inshiqaq", "totalVerses": 25 },
  { "id": 85, "name": "البروج", "englishName": "Al-Buruj", "totalVerses": 22 },
  { "id": 86, "name": "الطارق", "englishName": "At-Tariq", "totalVerses": 17 },
  { "id": 87, "name": "الأعلى", "englishName": "Al-Ala", "totalVerses": 19 },
  { "id": 88, "name": "الغاشية", "englishName": "Al-Ghashiya", "totalVerses": 26 },
  { "id": 89, "name": "الفجر", "englishName": "Al-Fajr", "totalVerses": 30 },
  { "id": 90, "name": "البلد", "englishName": "Al-Balad", "totalVerses": 20 },
  { "id": 91, "name": "الشمس", "englishName": "Ash-Shams", "totalVerses": 15 },
  { "id": 92, "name": "الليل", "englishName": "Al-Lail", "totalVerses": 21 },
  { "id": 93, "name": "الضحى", "englishName": "Ad-Duhaa", "totalVerses": 11 },
  { "id": 94, "name": "الشرح", "englishName": "Ash-Sharh", "totalVerses": 8 },
  { "id": 95, "name": "التين", "englishName": "At-Tin", "totalVerses": 8 },
  { "id": 96, "name": "العلق", "englishName": "Al-Alaq", "totalVerses": 19 },
  { "id": 97, "name": "القدر", "englishName": "Al-Qadr", "totalVerses": 5 },
  { "id": 98, "name": "البينة", "englishName": "Al-Bayyina", "totalVerses": 8 },
  { "id": 99, "name": "الزلزلة", "englishName": "Az-Zalzala", "totalVerses": 8 },
  { "id": 100, "name": "العاديات", "englishName": "Al-Adiyat", "totalVerses": 11 },
  { "id": 101, "name": "القارعة", "englishName": "Al-Qari'a", "totalVerses": 11 },
  { "id": 102, "name": "التكاثر", "englishName": "At-Takathur", "totalVerses": 8 },
  { "id": 103, "name": "العصر", "englishName": "Al-Asr", "totalVerses": 3 },
  { "id": 104, "name": "الهمزة", "englishName": "Al-Humaza", "totalVerses": 9 },
  { "id": 105, "name": "الفيل", "englishName": "Al-Fil", "totalVerses": 5 },
  { "id": 106, "name": "قريش", "englishName": "Quraysh", "totalVerses": 4 },
  { "id": 107, "name": "الماعون", "englishName": "Al-Ma'un", "totalVerses": 7 },
  { "id": 108, "name": "الكوثر", "englishName": "Al-Kawthar", "totalVerses": 3 },
  { "id": 109, "name": "الكافرون", "englishName": "Al-Kafirun", "totalVerses": 6 },
  { "id": 110, "name": "النصر", "englishName": "An-Nasr", "totalVerses": 3 },
  { "id": 111, "name": "المسد", "englishName": "Al-Masad", "totalVerses": 5 },
  { "id": 112, "name": "الإخلاص", "englishName": "Al-Ikhlas", "totalVerses": 4 },
  { "id": 113, "name": "الفلق", "englishName": "Al-Falaq", "totalVerses": 5 },
  { "id": 114, "name": "الناس", "englishName": "An-Nas", "totalVerses": 6 }
];
    